package org.team401.fms.data

import javafx.beans.property.SimpleIntegerProperty
import javafx.beans.property.SimpleStringProperty
import java.lang.StringBuilder
import java.security.SecureRandom
import java.util.*

class TeamAtEvent(number: Int) {
    companion object {
        val NONE = TeamAtEvent(0)

        //String of possible characters for a WPA key.  Generated by randomly mashing different sections of my keyboard.
        //Characters will be selected at random indices from this string to generate each team's WPA key.
        private val PASS_CHARS = "71398476904537401983479058613280746028755#@^%*)&!^)%*&^#@)%@%&)^qiwuytioyqwiuprypioqytIYWEIUTYIOQWYRPIahsfkashlkfjhsakhfJKSHDGJLKHALJFSDGmvzxbmzxczxNMVNZVNZXNNMBXCMN"
        private val PASS_LEN = 8
        private val random = SecureRandom()
    }

    private val number = SimpleIntegerProperty(number)
    private var wpaKey = SimpleStringProperty(null)

    fun getNumber() = number.get()
    fun setNumber(value: Int) = number.set(value)
    fun getWpaKey() = wpaKey.get()
    fun setWpaKey(value: String) = wpaKey.set(value)

    fun numberProperty() = number
    fun wpaKeyProperty() = wpaKey

    /**
     * Generates a random WPA key for this team
     */
    fun generateWpaKey() {
        val sb = StringBuilder()
        for (i in 0 until PASS_LEN) {
            sb.append(PASS_CHARS[random.nextInt(PASS_CHARS.length)]) //Append a random character to the password
        }
        wpaKey.set(sb.toString())
    }
}

fun main() {
    val team = TeamAtEvent(401)

    team.generateWpaKey()
    println(team.getWpaKey())
}